CREATE TABLE IF NOT EXISTS orders
(
    id  INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_name VARCHAR (255) NOT NULL,
    pizza_type VARCHAR(100) NOT NULL,
    pizza_size VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PREPARING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS toppings
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    topping VARCHAR(100) NOT NULL
);
